server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  jwt:
    secret: e253645a97f98c5ac9d94c7cb6fe47adef76834f1ebf312d9617564096f443ad
    access-token-expire-time: 7200000
    refresh-token-expire-time: 172800000



#CORS 설정
cors:
  allowed-origins: http://localhost:5173


# S3
cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
      path:
        profile: profile
        event: event
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

open-data:
  api-key: ${OPENDATA_API_KEY}
  base-url: https://api.odcloud.kr/api/nts-businessman/v1

ai:
  server:
    base-url: http://13.124.81.157:8000/